packages:
  - docs
  - playground
  - packages/**
catalog:
  '@antfu/eslint-config': ^3.0.0
  '@iconify-json/carbon': ^1.1.37
  '@nuxt/devtools': ^1.3.14
  '@nuxt/kit': ^3.13.0
  '@nuxt/schema': ^3.13.0
  '@types/fs-extra': ^11.0.4
  '@types/node': ^22.5.0
  bumpp: ^9.5.2
  consola: ^3.2.3
  esno: ^4.7.0
  execa: ^8.0.1
  fs-extra: ^11.2.0
  lint-staged: ^15.2.9
  nuxt: ^3.13.0
  ofetch: ^1.3.4
  pathe: ^1.1.2
  simple-git: ^3.25.0
  simple-git-hooks: ^2.11.1
  std-env: ^3.7.0
  taze: ^0.16.6
  typescript: ^5.5.4
  unbuild: ^2.0.0
  vitepress: ^1.3.3
  vitepress-plugin-group-icons: ^1.0.3
  vitest: ^2.0.5
  vue: ^3.4.38
